package com.example.directory.model.bean;

import org.jspresso.framework.util.bean.AbstractPropertyChangeCapable;
import com.example.directory.model.Activity;

import java.util.HashSet;
import java.util.Set;
import com.example.directory.model.Contact;

/**
 * Generated by SJSPlug for Jspresso
 */
public class ActivityStat extends AbstractPropertyChangeCapable {

  private Activity activity;
  private Set<Contact> contacts = new HashSet<Contact>();
  
  public ActivityStat(Activity activity) {
    this.activity = activity;
  }
  
  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Activity getActivity() {
    return activity;
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Set<Contact> getContacts() {
    return contacts;
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Integer getContactsCount() {
    return getContacts().size();
  }
  
}
