package com.example.directory.model.bean;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

import org.jspresso.framework.util.bean.AbstractPropertyChangeCapable;

import com.example.directory.model.Activity;
import com.example.directory.model.Category;
import com.example.directory.model.Contact;

/**
 * Generated by SJSPlug for Jspresso
 */
public class CategoryStat extends AbstractPropertyChangeCapable {

  private Category category;
  private Set<ActivityStat> activities = new HashSet<ActivityStat>();
  
  public CategoryStat(Category category) {
    this.category = category;
    
    HashMap<Activity, ActivityStat> activitiesTemp = new HashMap<Activity, ActivityStat>();
    for (Contact c : category.getContacts()) {
      for (Activity a : c.getActivities()) {
        ActivityStat as = activitiesTemp.get(a);
        if (as == null) {
          as = new ActivityStat(a);
          activitiesTemp.put(a, as);
        }
        as.getContacts().add(c);
      }
    }    
    activities.addAll(activitiesTemp.values());
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Category getCategory() {
    return category;
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Set<ActivityStat> getActivities() {
    return activities;
  }
  
}
