package com.example.directory.model.bean;

import org.jspresso.framework.util.bean.AbstractPropertyChangeCapable;
import java.util.Set;
import com.example.directory.model.Category;
import com.example.directory.model.Activity;

/**
 * Generated by SJSPlug for Jspresso
 */
public class Statistics extends AbstractPropertyChangeCapable {

  private Set<Category> categories;
  private Set<Activity> activities;

  public Statistics(Set<Category> categories, Set<Activity> activities) {
    this.categories = categories;
    this.activities = activities;
  }
  
  
  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Set<Category> getCategories() {
    return categories;
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Set<Activity> getActivities() {
    return activities;
  }

}
