package com.example.directory.model.bean;

import org.jspresso.framework.util.bean.AbstractPropertyChangeCapable;

import java.util.HashSet;
import java.util.Set;
import com.example.directory.model.Category;
import com.example.directory.model.Activity;

/**
 * Generated by SJSPlug for Jspresso
 */
public class Statistics extends AbstractPropertyChangeCapable {

  private Set<CategoryStat> categoriesStats;
  private Set<Activity> activities;

  public Statistics(Set<Category> categories, Set<Activity> activities) {
    this.activities = activities;

    categoriesStats = new HashSet<CategoryStat>();
    for (Category c : categories) {
      CategoryStat cs = new CategoryStat(c);
      categoriesStats.add(cs);
    }
    
  }
  
  
  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Set<CategoryStat> getCategories() {
    return categoriesStats;
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Set<Activity> getActivities() {
    return activities;
  }

}
