package com.example.directory.model.extension;

import org.jspresso.framework.model.component.AbstractComponentExtension;

import com.example.directory.model.Activity;
import com.example.directory.model.Contact;

/**
 * Generated by SJSPlug for Jspresso
 */
public class ActivityExtension extends AbstractComponentExtension<Activity> {

  public ActivityExtension(Activity component) {
    super(component);

    registerNotificationForwarding(component, "contacts", "contactsCount");
  }

  /**
   * generated by SJSPlug for Jspresso
   * 
   * @return
   */
  public Integer getContactsCount() {
    return getComponent().getContacts() != null ? getComponent().getContacts().size() : 0;
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Integer getContactsCountActive() {
    int i=0;
    if (getComponent().getContacts() != null) {
      for (Contact c : getComponent().getContacts()) {
        if ( "0".equals(c.getStatus())) {
          i++;
        }
      }
    }
    return i;
  }

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Integer getContactsCountInactive() {
    return getContactsCount() - getContactsCountActive();
  }

}
