package com.example.directory.model.extension;

import org.jspresso.framework.model.component.AbstractComponentExtension;

import com.example.directory.model.Activity;

/**
 * Generated by SJSPlug for Jspresso
 */
public class ActivityExtension extends AbstractComponentExtension<Activity> {

  public ActivityExtension(Activity component) {
    super(component);

    registerNotificationForwarding(component, "contacts", "contactsCount");
  }

  /**
   * generated by SJSPlug for Jspresso
   * 
   * @return
   */
  public Integer getContactsCount() {
    return getComponent().getContacts() != null ? getComponent().getContacts()
        .size() : 0;
  }

}
