package com.example.directory.model.extension;

import org.jspresso.framework.model.component.AbstractComponentExtension;

import com.example.directory.model.Address;

/**
 * Generated by SJSPlug for Jspresso
 */
public class AddressExtension extends AbstractComponentExtension<Address> {

	public AddressExtension(Address component) {
		super(component);

		registerNotificationForwarding(component, "street", "fullDescription");
		registerNotificationForwarding(component, "city", "fullDescription");
		registerNotificationForwarding(component, "zip", "fullDescription");
		registerNotificationForwarding(component, "country", "fullDescription");
	}

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public String getFullDescription() {
    StringBuffer sb = new StringBuffer();
    if (getComponent().getStreet()!=null) {
      sb.append(getComponent().getStreet()).append(' ');
    }
    if (getComponent().getCity()!=null) {
      sb.append(getComponent().getCity()).append(' ');
    }
    if (getComponent().getZip()!=null) {
      sb.append(getComponent().getZip()).append(' ');
    }
    if (getComponent().getCountry()!=null) {
      sb.append(getComponent().getCountry());
    }
    return sb.toString().trim();
  }
  
}
