package com.example.directory.model.extension;

import org.jspresso.framework.model.component.AbstractComponentExtension;

import com.example.directory.model.Customer;
import com.example.directory.model.Address;

/**
 * Generated by SJSPlug for Jspresso
 */
public class CustomerExtension extends AbstractComponentExtension<Customer> {

	public CustomerExtension(Customer component) {
		super(component);

		registerNotificationForwarding(component, "addresses", "mainAddress");
	}

  /**
   * generated by SJSPlug for Jspresso
   * @return
   */
  public Address getMainAddress() {    
    if (getComponent().getAddresses() != null && !getComponent().getAddresses().isEmpty()) {
      return getComponent().getAddresses().iterator().next();
    }
    else {
      return null;
    }
  }
  
}
